# Generated by Django 4.1.7 on 2023-03-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('tag', models.CharField(choices=[('Bottoms', 'Bottoms'), ('Top', 'Top'), ('Shoes', 'Shoes'), ('Accessory', 'Accessory')], max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('image', models.ImageField(default='/HoosExchangeSite/images/noImage.png', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='newModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
