# Generated by Django 4.1.7 on 2023-03-26 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HoosExchangeSite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='item_name',
        ),
    ]
