# Generated by Django 4.1.7 on 2023-03-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoosExchangeSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='static/HoosExchangeSite/images/noImage.png', upload_to='images'),
        ),
    ]
