# Generated by Django 4.1.7 on 2023-03-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoosExchangeSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmodel',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='newmodel',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newmodel',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='newmodel',
            name='tag',
            field=models.CharField(choices=[('Bottoms', 'Bottoms'), ('Top', 'Top'), ('Shoes', 'Shoes'), ('Accessory', 'Accessory')], default='', max_length=100),
        ),
    ]
