# Generated by Django 4.1.7 on 2023-03-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoosExchangeSite', '0002_listing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(choices=[('Bottoms', 'Bottoms'), ('Top', 'Top'), ('Shoes', 'Shoes'), ('Accessory', 'Accessory')], max_length=100),
        ),
    ]
