# Generated by Django 4.1.7 on 2023-03-26 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HoosExchangeSite', '0002_newmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='person_name',
            new_name='name',
        ),
    ]
