# Generated by Django 4.1.7 on 2023-03-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoosExchangeSite', '0002_newmodel_description_newmodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmodel',
            name='image',
            field=models.ImageField(default='/HoosExchangeSite/images/noImage.png', upload_to='images'),
        ),
    ]
