# Generated by Django 4.1.7 on 2023-03-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoosExchangeSite', '0003_remove_listing_image_alter_listing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='tag',
            field=models.CharField(choices=[('Bottoms', 'Bottoms'), ('Top', 'Top'), ('Shoes', 'Shoes'), ('Accessory', 'Accessory')], max_length=100),
        ),
    ]
