# Generated by Django 4.1.7 on 2023-03-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoosExchangeSite', '0003_newmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='tag',
            field=models.CharField(choices=[('Bottoms', 'Bottoms'), ('Top', 'Top'), ('Shoes', 'Shoes'), ('Accessory', 'Accessory'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='newmodel',
            name='phone_number',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='newmodel',
            name='tag',
            field=models.CharField(choices=[('Bottoms', 'Bottoms'), ('Top', 'Top'), ('Shoes', 'Shoes'), ('Accessory', 'Accessory'), ('Other', 'Other')], default='', max_length=100),
        ),
    ]
