# Generated by Django 4.1.7 on 2023-03-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoosExchangeSite', '0004_alter_listing_name_alter_listing_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='key',
            field=models.IntegerField(default=0),
        ),
    ]
