# Generated by Django 4.1.7 on 2023-03-26 01:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('HoosExchangeSite', '0007_alter_listing_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='key',
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f8406727-7e8d-4337-a39e-7dad940b1def'), editable=False, primary_key=True, serialize=False),
        ),
    ]
