# Generated by Django 4.1.7 on 2023-03-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoosExchangeSite', '0010_alter_listing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='/HoosExchangeSite/images/noImage.png', upload_to='images'),
        ),
    ]
