# Generated by Django 4.1.7 on 2023-03-26 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HoosExchangeSite', '0011_listing_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='name',
            new_name='person_name',
        ),
    ]
