# Generated by Django 4.1.7 on 2023-03-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoosExchangeSite', '0012_rename_name_listing_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='item_name',
            field=models.CharField(default='no name', max_length=100),
        ),
    ]
